name: login_design
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_signin_button: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  google_fonts: ^6.2.1

flutter:
  uses-material-design: true

  assets:
    - c:\Users\ADMIN\Documents\flutterDev\testLogin\login_design\assets\backgrounds\bginicio.jpg
    - assets\backgrounds\fondowelcome.png
